[build-system]
requires = ["setuptools >= 61",
            "wheel",
            "setuptools_scm[toml]>=6.0",
            ]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/story_writer/_version.py"
